### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by agibsonccc** [TomaszAugustyn/call-stack-logger#4]
Hi Tomas:

Great project and super useful for what I'm currently doing.  
Can you add a license to the repository? I don't see one anywhere. Thanks!

**Comment by TomaszAugustyn** [comment]
Hello @agibsonccc !
Thank you so much, I'm really happy you find it useful.
I've added the license and described it [here](https://github.com/TomaszAugustyn/call-stack-logger#balance_scale-copyright-and-license).

**Comment by agibsonccc** [comment]
Not enough with that license :) I will use it for my use case and remove it afterwards. Best of luck though!

**Comment by TomaszAugustyn** [comment]
Thanks.
